tunnel: b5410096-1567-4795-b081-68b1cf5cbf74
credentials-file: /etc/cloudflared/cert.json

ingress:
  # Traffic to the tunnel domain is forwarded to the Traefik container
  # which then routes it to the correct service based on Host labels.
  - hostname: laptopchris.alpacapurpura.lat
    service: http://visionarias_brain:8000
    
  # Default rule
  - service: http_status:404
